version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - database
            - redis
        networks:
            - network-app
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE=example-app
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - db-data:/var/lib/mysql
        networks:
            - network-app
    phpmyadmin:
        platform: linux/x86_64
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - database
        ports:
            - 91:80
        environment:
            PMA_PORT: 3306
            PMA_HOST: database
        networks:
            - network-app
    redis:
        container_name:  redis
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass  "secret"
        ports:
            - 6380:6379
        networks:
            - network-app
volumes:
    db-data: ~
networks:
  network-app:
    driver: bridge